services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: nl2sql-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: nl2sql-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped