const normalize = (value) =>
    String(value ?? "").trim().toLowerCase();

const quoteIdentifier = (value, dialect) => {
    const identifier = String(value ?? "").trim();

    if (dialect === "mysql") {
        return `\`${identifier.replace(/`/g, "``")}\``;
    }

    if (dialect === "sqlite") {
        return `"${identifier.replace(/"/g, '""')}"`;
    }

    return `"${identifier.replace(/"/g, '""')}"`;
};

const getTableName = (node) =>
    String(node?.data?.tableName ?? node?.id ?? "").trim();

const getColumns = (node) =>
    Array.isArray(node?.data?.columns)
        ? node.data.columns
        : [];

const getColumnName = (column) =>
    String(column?.name ?? "").trim();

const getColumnType = (column) =>
    String(column?.type ?? "VARCHAR")
        .trim()
        .toUpperCase();

const getColumnTypeSQL = (column, dialect) => {
    const type = getColumnType(column);

    if (type === "VARCHAR") {
        const length = Number(column?.length);

        if (Number.isFinite(length) && length > 0) {
            return `VARCHAR(${length})`;
        }

        return "VARCHAR(255)";
    }

    if (type === "DECIMAL" || type === "NUMERIC") {
        const precision = Number(column?.precision ?? 10);
        const scale = Number(column?.scale ?? 2);

        if (
            Number.isFinite(precision) &&
            Number.isFinite(scale) &&
            precision > 0 &&
            scale >= 0 &&
            scale <= precision
        ) {
            return `DECIMAL(${precision}, ${scale})`;
        }

        return "DECIMAL(10, 2)";
    }

    if (
        type === "INT" ||
        type === "INTEGER" ||
        type === "BIGINT" ||
        type === "SMALLINT"
    ) {
        return type;
    }

    if (type === "TEXT") {
        return "TEXT";
    }

    if (type === "BOOLEAN" || type === "BOOL") {
        return dialect === "mysql" ? "BOOLEAN" : "BOOLEAN";
    }

    if (type === "DATE") {
        return "DATE";
    }

    if (type === "DATETIME") {
        return dialect === "postgresql"
            ? "TIMESTAMP"
            : "DATETIME";
    }

    if (type === "TIMESTAMP") {
        return "TIMESTAMP";
    }

    if (type === "TIME") {
        return "TIME";
    }

    if (type === "FLOAT") {
        return "FLOAT";
    }

    if (type === "DOUBLE") {
        return "DOUBLE";
    }

    if (type === "JSON") {
        return "JSON";
    }

    return type || "VARCHAR(255)";
};

const getDefaultValue = (column) => {
    if (
        column?.defaultValue === undefined ||
        column?.defaultValue === null ||
        String(column.defaultValue).trim() === ""
    ) {
        return null;
    }

    const value = String(column.defaultValue).trim();

    if (
        value === "NULL" ||
        value === "CURRENT_TIMESTAMP" ||
        value === "CURRENT_DATE" ||
        value === "CURRENT_TIME"
    ) {
        return value;
    }

    if (/^-?\d+(\.\d+)?$/.test(value)) {
        return value;
    }

    if (value === "TRUE" || value === "FALSE") {
        return value;
    }

    return `'${value.replace(/'/g, "''")}'`;
};

const getAutoIncrementSQL = (column, dialect) => {
    if (!column?.autoIncrement) {
        return "";
    }

    if (dialect === "postgresql") {
        const type = getColumnType(column);

        if (type === "BIGINT") {
            return " GENERATED BY DEFAULT AS IDENTITY";
        }

        return " GENERATED BY DEFAULT AS IDENTITY";
    }

    if (dialect === "mysql") {
        return " AUTO_INCREMENT";
    }

    if (
        column?.isPrimaryKey &&
        ["INTEGER", "INT"].includes(getColumnType(column))
    ) {
        return " AUTOINCREMENT";
    }

    return "";
};

const getRelation = (edge) =>
    normalize(edge?.data?.relation) === "optional"
        ? "optional"
        : "required";

const buildForeignKeyConstraint = (
    edge,
    sourceNode,
    targetNode,
    sourceColumn,
    targetColumn,
    dialect
) => {
    const sourceTable = getTableName(sourceNode);
    const targetTable = getTableName(targetNode);
    const sourceColumnName = getColumnName(sourceColumn);
    const targetColumnName = getColumnName(targetColumn);

    const constraintName =
        edge?.data?.constraintName ||
        `fk_${sourceTable}_${sourceColumnName}`;

    const relation = getRelation(edge);

    let sql =
        `CONSTRAINT ${quoteIdentifier(constraintName, dialect)} ` +
        `FOREIGN KEY (${quoteIdentifier(sourceColumnName, dialect)}) ` +
        `REFERENCES ${quoteIdentifier(targetTable, dialect)} ` +
        `(${quoteIdentifier(targetColumnName, dialect)})`;

    if (relation === "optional") {
        sql += " ON DELETE SET NULL";
    } else {
        sql += " ON DELETE CASCADE";
    }

    sql += " ON UPDATE CASCADE";

    return sql;
};

const buildCreateTable = (
    node,
    edges,
    nodeMap,
    dialect
) => {
    const tableName = getTableName(node);
    const columns = getColumns(node);

    const definitions = [];

    columns.forEach((column) => {
        const columnName = getColumnName(column);

        if (!columnName) {
            return;
        }

        let definition =
            `${quoteIdentifier(columnName, dialect)} ` +
            getColumnTypeSQL(column, dialect);

        definition += getAutoIncrementSQL(
            column,
            dialect
        );

        if (column.isPrimaryKey) {
            definition += " PRIMARY KEY";
        }

        if (column.isUnique && !column.isPrimaryKey) {
            definition += " UNIQUE";
        }

        if (column.isNullable === false || column.isPrimaryKey) {
            definition += " NOT NULL";
        }

        const defaultValue = getDefaultValue(column);

        if (defaultValue !== null) {
            definition += ` DEFAULT ${defaultValue}`;
        }

        definitions.push(definition);
    });

    const foreignKeys = [];

    edges.forEach((edge) => {
        if (edge?.source !== node.id) {
            return;
        }

        const sourceNode = nodeMap.get(edge.source);
        const targetNode = nodeMap.get(edge.target);

        if (!sourceNode || !targetNode) {
            return;
        }

        const sourceColumn = getColumns(sourceNode).find(
            (column) => column.id === edge.sourceHandle
        );

        const targetColumn = getColumns(targetNode).find(
            (column) => column.id === edge.targetHandle
        );

        if (!sourceColumn || !targetColumn) {
            return;
        }

        foreignKeys.push(
            buildForeignKeyConstraint(
                edge,
                sourceNode,
                targetNode,
                sourceColumn,
                targetColumn,
                dialect
            )
        );
    });

    definitions.push(...foreignKeys);

    const tableOptions =
        dialect === "mysql"
            ? "\nENGINE=InnoDB"
            : "";

    return (
        `CREATE TABLE ${quoteIdentifier(tableName, dialect)} (\n` +
        definitions
            .map((definition) => `    ${definition}`)
            .join(",\n") +
        `\n)${tableOptions};`
    );
};

export function generateSQL(
    nodes = [],
    edges = [],
    dialect = "postgresql"
) {
    const normalizedDialect = [
        "postgresql",
        "mysql",
        "sqlite",
    ].includes(normalize(dialect))
        ? normalize(dialect)
        : "postgresql";

    if (!Array.isArray(nodes) || nodes.length === 0) {
        return "";
    }

    const safeEdges = Array.isArray(edges) ? edges : [];

    const nodeMap = new Map(
        nodes
            .filter((node) => node?.id)
            .map((node) => [node.id, node])
    );

    const validNodes = nodes.filter(
        (node) => getTableName(node)
    );

    const statements = [];

    statements.push(
        `-- Generated SQL (${normalizedDialect})`
    );

    statements.push("");

    validNodes.forEach((node, index) => {
        statements.push(
            buildCreateTable(
                node,
                safeEdges,
                nodeMap,
                normalizedDialect
            )
        );

        if (index < validNodes.length - 1) {
            statements.push("");
        }
    });

    return statements.join("\n");
}

export function generateCreateTableSQL(
    node,
    nodes = [],
    edges = [],
    dialect = "postgresql"
) {
    if (!node) {
        return "";
    }

    const nodeMap = new Map(
        nodes
            .filter((item) => item?.id)
            .map((item) => [item.id, item])
    );

    if (!nodeMap.has(node.id)) {
        nodeMap.set(node.id, node);
    }

    return buildCreateTable(
        node,
        Array.isArray(edges) ? edges : [],
        nodeMap,
        normalize(dialect) || "postgresql"
    );
}

export default generateSQL;